###
POST http://localhost:3333/raffles
Content-Type: application/json

{
  "title": "Rifa de Carnaval",
  "email": "diana@tal.com",
  "password": "123",
  "maximumNumbers": 100,
  "drawDate": "2024/08/14",
  "prizePool": "Um Kit Homem sagaz"
}

###
POST http://localhost:3333/raffles/2c87eccc-405a-4cdd-a365-a48557b2bb05/tickets
Content-Type: application/json

{
  "number": 7,
  "name": "Nikolas",
  "email": "Nik@gmail.com",
  "celNumber": "86999887766"
}

###
GET http://localhost:3333/raffles/2c87eccc-405a-4cdd-a365-a48557b2bb05

###
GET http://localhost:3333/raffles/2c87eccc-405a-4cdd-a365-a48557b2bb05/tickets/7

###
GET http://localhost:3333/raffles
