###
POST http://localhost:3333/raffles
Content-Type: application/json

{
  "title": "Rifa de Reveion",
  "email": "diana@tal.com",
  "password": "123",
  "maximumNumbers": 100,
  "drawDate": "2024/08/14",
  "prizePool": "Um Kit Homem sagaz"
}

###
POST http://localhost:3333/raffles/32c0e9a7-be84-4181-a83d-b870cd5a2e04/tickets
Content-Type: application/json

{
  "number": 7,
  "name": "Nikolas",
  "email": "Nik@gmail.com",
  "celNumber": "86999887766"
}

###
GET http://localhost:3333/raffles/f1bede08-692d-41a0-9075-8b94e5437234

###
GET http://localhost:3333/raffles/f1bede08-692d-41a0-9075-8b94e5437234/tickets/7

###
GET http://localhost:3333/raffles
